### ISSUE TITLE
Elimination Message Bug

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#373] opened 2024-06-03 03:33 UTC
The elimination message saying "X got Eliminated" displays when a player connects to the match (from none to a role) just when the round starts

**Comment by EmeraldLoc** [comment] 2024-06-04 19:37
Wait, huh?

**Comment by TheMan6900** [comment] 2024-06-04 19:59
If a player switches from the none team to the eliminated team, as the match starts, itll display that their eliminated.

**Comment by EmeraldLoc** [comment] 2024-06-04 20:01
> as the match starts

What is this exactly, is it a second before the match starts, a second after, or anywhere in between?

**Comment by TheMan6900** [comment] 2024-06-04 20:06
pretty sure its anywhere in between, if not its probably the other too

**Comment by EmeraldLoc** [comment] 2024-06-19 20:53
Has this occurred since then?

**Comment by TheMan6900** [comment] 2024-06-19 21:13
Yea

**Comment by TheMan6900** [comment] 2024-06-19 21:13
Like 3 times

**Comment by EmeraldLoc** [comment] 2024-06-19 22:49
Does the player actually get eliminated, or is it immediately reversed? What gamemodes do this happen in?

**Comment by TheMan6900** [comment] 2024-06-20 20:57
They do get eliminated and happens in every gamemode where you CAN get eliminated

**Comment by EmeraldLoc** [comment] 2024-06-20 20:58
Wait so then what's the bug here?

**Comment by TheMan6900** [comment] 2024-06-20 21:37
It's not supposed announce that there eliminated with a pop up

**Comment by EmeraldLoc** [comment] 2024-06-20 21:38
You died while the round was started..... so wouldn't that be correct?

**Comment by TheMan6900** [comment] 2024-06-20 21:40
I mean, you die because you joined the game, I don't feel like that should be considered you dying 💀

**Comment by EmeraldLoc** [comment] 2024-06-20 23:02
> you die because you joined the game

The popup doesn't trigger when you join the game, you sure the player isn't dying beforehand?

**Comment by TheMan6900** [comment] 2024-06-21 01:01
Im 95% sure they ain't just joining and dying in 2 seconds

**Comment by EmeraldLoc** [comment] 2024-06-21 02:13
Well if you could try to reproduce it, that'd help a bit :)

**Comment by TheMan6900** [comment] 2024-06-25 05:48
Tried replicating to not avail

**Comment by EmeraldLoc** [comment] 2024-07-07 02:45
Gonna close this, I believe there's an error in how you are interpreting what's happening here, I don't think it's the mod at fault. If you can send a video I'll reopen this.

**Closed by EmeraldLoc** 2024-07-07 02:45 UTC
Labels: bug
