### ISSUE TITLE
Tagger Lag and Lag in general

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#123] opened 2024-05-24 01:03 UTC
For some reason, for gamemodes that have traditional tagger systems (tag, freeze tag, infection, hot potato, juggernaut, sardine, hunt, and probably search) have werid problems with lag, halving the framerate.

**Comment by EmeraldLoc** [comment] 2024-05-24 01:05
Open up the lua profiler in coopdx to see what mod you have is using the most performance.

**Comment by TheMan6900** [comment] 2024-05-24 01:09
Tag uses almost double, TMK's resources, 2000 to 4000

**Comment by EmeraldLoc** [comment] 2024-05-24 01:10
Were you looking at the lua profiler during the lag, or when it was running fine? I should join your lobby

**Comment by TheMan6900** [comment] 2024-05-24 01:11
not for the lag. this would be better if you joinned to analysis.

**Comment by EmeraldLoc** [comment] 2024-05-31 16:55
Has this lag occurred without tmk?

**Comment by TheMan6900** [comment] 2024-05-31 17:05
yeah

**Comment by TheMan6900** [comment] 2024-05-31 17:07
tmk is incredibly optimized so,

**Comment by TheMan6900** [comment] 2024-05-31 17:19
It might honestly just be this

"The starting in timer? While sure it isn’t optimized great, that won’t be the problem with syncing, most mods sync the timer every frame, it’s a bad, but common practice. Generally, syncing problems only occur when you have a bad connection. When I feel like it, I’ll take some time to optimize some of the syncing, nonetheless it isn’t really a problem, and works fine if you have a decent connection,"

**Comment by EmeraldLoc** [comment] 2024-05-31 18:19
> tmk is incredibly optimized so,
Doubt
> It might honestly just be this
I 100% doubt this is the case. Have you actually encountered this issue without tmk, or are you saying that because it's "incredibly optimized."

**Comment by TheMan6900** [comment] 2024-05-31 18:37
> I 100% doubt this is the case. Have you actually encountered this issue without tmk, or are you saying that because it's "incredibly optimized."

nope just saying the truth

**Comment by TheMan6900** [comment] 2024-05-31 18:37
I happens both with it and without it.

**Comment by EmeraldLoc** [comment] 2024-05-31 18:42
Is this reproducible, if so, how

**Comment by TheMan6900** [comment] 2024-05-31 19:28
I dont really know, it just happens randomly, most commonly with assassins

**Comment by EmeraldLoc** [comment] 2024-05-31 21:54
There was a much more severe bug with assassins so it makes sense that game mode would contain a problem. Will look into

**Comment by EmeraldLoc** [comment] 2024-06-04 19:35
Does this happen with a low player count, or only with a high player count?

**Comment by EmeraldLoc** [comment] 2024-06-08 00:38
Any updates on this?

**Comment by TheMan6900** [comment] 2024-06-08 00:53
No updates for now, Im pretty sure its something to do with assassins, it most often happens withs high player counts

**Comment by EmeraldLoc** [comment] 2024-06-08 00:55
And is that during the round state being active or is it during the state being set to wait?

**Comment by TheMan6900** [comment] 2024-06-08 00:56
most often happens in the 15 second waiting phase

**Comment by EmeraldLoc** [comment] 2024-06-08 00:57
I thought I fixed this a long time ago... except before it happened to everyone and not just the host, will look into

**Comment by EmeraldLoc** [comment] 2024-06-08 01:07
Ok, I just made massive optimizations to assassins. This lag should be fixed now.

**Closed by EmeraldLoc** 2024-06-08 01:07 UTC
Labels: bug
