### ISSUE TITLE
Cant Auto Scroll Downwards?

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#910] opened 2024-07-15 03:47 UTC
Weird thing I noticed while messing around with the pause menu, but you cant auto scroll downwards on the pause menu like you can going up the menu (also uh, add auto scrolling for dpad in the settings menu, thanks)

https://github.com/user-attachments/assets/3889f16d-02c3-46e6-b623-2e33a2337291

**Comment by EmeraldLoc** [comment] 2024-07-21 00:12
Unable to reproduce this. If you were using the dpad, that's known.

**Comment by EmeraldLoc** [comment] 2024-07-21 00:14
Made auto scroll work with dpad, gonna close this.

**Closed as completed by EmeraldLoc** 2024-07-21 00:14 UTC
Labels: bug
