### ISSUE TITLE
Keep track of stats

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#142] opened 2024-05-25 22:28 UTC
If a match ends abruptly (say if your in a 3 player server and the tagger leaves) youll still earn the win/lose you got based on your position at the time when the match ended.

**Comment by EmeraldLoc** [comment] 2024-05-25 23:25
> if your in a 3 player server and the tagger leaves

This is the root cause, and this should be addressed instead.

**Closed by EmeraldLoc** 2024-05-25 23:25 UTC
