### ISSUE TITLE
SM74 Tag Pack Issue

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#82] opened 2024-05-20 19:38 UTC
Tag packs (like tag - arena maps, tag - mcdonalds, and tag - bitfort) load twice for SM74 specifically

**Comment by EmeraldLoc** [comment] 2024-05-20 21:17
I am unable to reproduce with v2.32 and sm74. Are there any other things you do to get this to happen?

**Comment by TheMan6900** [comment] 2024-05-20 21:21
Im not sure what produces this problem, it may just be a random issue, since it often (not all the time) happens in my server

**Comment by EmeraldLoc** [comment] 2024-05-22 03:34
Gonna close this cuz it seems random. If you find a reproducible way to get this bug, reopen this issue.

**Closed by EmeraldLoc** 2024-05-22 03:34 UTC
Labels: bug
