### ISSUE TITLE
Make the random start option unable to pick the currently active level

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1517] opened 2024-12-22 04:03 UTC
Just makes sense and removes some annoyance

**Comment by EmeraldLoc** [comment] 2024-12-26 21:24
This should already be happening, is it not?

**Comment by TheMan6900** [comment] 2024-12-26 21:32
It occasionally doesn't happen

**Comment by EmeraldLoc** [comment] 2024-12-31 23:30
Unable to reproduce this, assuming either fixed in 2.4.1 or you're interpreting this wrong. I went to a hack with just 4 levels and was unable to reproduce it, and that's a 1/4 chance.

**Closed as not planned by EmeraldLoc** 2024-12-31 23:30 UTC
