### ISSUE TITLE
Make the spring air control more responsive 

### ISSUE THREAD

**Issue by TheMan6900** [EmeraldLoc/tag#1413] opened 2024-09-28 03:29 UTC
https://github.com/user-attachments/assets/17a89437-5879-4a38-9ec7-a57931b0bb20
(dont ask why the video quality takes such a nose dive for like 3 seconds)

**Comment by EmeraldLoc** [comment] 2024-09-28 22:44
Lets see everything wrong with this issue

1. Duplicate of https://github.com/EmeraldLoc/tag/issues/585
2. The video shows nothing. What am I meant to take out of it? Nothing is said of it, just a video without context.
3. Without a narrow description, say.ing to make it more responsive gives no info on what you're actually looking for

Closing, same reason as in #585

**Closed as not planned by EmeraldLoc** 2024-09-28 22:44 UTC
